FROM

USER root

WORKDIR /home/root/

RUN apt-get update && apt-get install sudo -y && apt-get install curl -y
RUN useradd -m -s /bin/bash mongo
RUN usermod -aG sudo mongo

EXPOSE 4200

RUN apt-get install curl -y
RUN apt install git -y
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt install nodejs -y
Run apt install build-essential -y
RUN yes | npm install -g @angular/cli
WORKDIR /home/mongo/
RUN rm -rf poolmanage-ui
RUN git clone https://github.com/yamileon/poolmanage-ui.git
RUN ls -la
WORKDIR /home/mongo/poolmanage-ui/
RUN ls -la
RUN git checkout furr-dev2
RUN yes | npm install -y
RUN ng build

FROM 
